### ISSUE TITLE
Dedent does not work on elseif or else statements

### ISSUE THREAD

**Issue by WizardJosh** [mghdotdev/vscode-miva-ide#46]
When using Miva Script starting an MvIF conditional indents correctly with any line after. Using an MvELSEIF or MvELSE after
does not dedent to line up correctly. Not a high priority i know, but gets annoying having large else if conditionals.

**Comment by mghdotdev** [comment]
Thanks, Josh! I am glad you like the plugin. We are going to add your suggestions to the list.

We will address these issues in the next release.

**Comment by mghdotdev** [comment]
@WizardJosh 

This issue should be resolved in v1.1.0
