### ISSUE TITLE
Text highlighting stops working after using { in a literal.

### ISSUE THREAD

**Issue by WizardJosh** [mghdotdev/vscode-miva-ide#47]
If one uses open curly in a literal expression the text highlighting stops working correctly. It acts as if everything is being quoted.
For Instance glosub(VariableName,'{','') 
After this statement all the text color changes do not take effect as they should. All variable names show the same color as literal expressions. You cannot easily determine what is a variable or literal. Even function calls show the same color as literal. Its very difficult to read anytime this happens. I know my issues are low on the priority list. Just fyi i love this ide, it is so nice to finally have one.

**Comment by mghdotdev** [comment]
Thanks, Josh! I am glad you like the plugin. We are going to add your suggestions to the list.

We will address these issues in the next release.

**Comment by mghdotdev** [comment]
Fixed in version 1.3.0

#58
