### ISSUE TITLE
miva_joinstring flags have invalid options

### ISSUE THREAD

**Issue by steveosoule** [mghdotdev/vscode-miva-ide#52]
The options listed for miva_joinstring's flags are invalid (ex `'trim','ltrim','rtrim','lower','upper','insensitive'`) 

https://github.com/mghdotdev/vscode-miva-ide/blob/main/snippets/builtins.snippets.json#L1823

The available flags are `'escape','insensitive','noempty'`

**Comment by mghdotdev** [comment]
Updated in #57
