### ISSUE TITLE
Documentation References

### ISSUE THREAD

**Issue by WizardJosh** [mghdotdev/vscode-miva-ide#80]
Love the most recent changes btw. This is not an Issue, just a question but i cold not find where to simply ask one. Is there a way
to turn off the documentation reference popups that describe what an if statement is or a while loop?

**Comment by mghdotdev** [comment]
No, I don't have any way of disabling hover documentation on a tag-by-tag basis.

A setting could be added to disable hover documentation for all tags or fully disable all hover documentation for everything (functions, items, tags, variables, etc...).

**Comment by WizardJosh** [comment]
I for one would love a way to control turning it off. It can be very distracting when trying to read through code and these pop up.
